# Generated by Django 5.2.17 on 2026-08-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='providers', to='services.service'),
        ),
    ]
